version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "building"
  pre_build:
    commands:
      - npm install
      - echo "insatlled npm packages"
  build:
    commands:
      - echo "zipping the application"
      - zip -r lambda.zip .
