version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "building"
  pre_build:
    commands:
      - npm install --no-progress --silent
      - echo "insatlled npm packages"
  build:
    commands:
      - echo "zipping the application"
      - zip -r lambda.zip .
